"""empty message

Revision ID: 01878331fc22
Revises: 
Create Date: 2019-09-11 03:19:10.258943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01878331fc22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'meal', 'room', ['room'], ['id'])
    op.create_foreign_key(None, 'person', 'room', ['room'], ['id'])
    op.create_foreign_key(None, 'transaction', 'room', ['room'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_constraint(None, 'meal', type_='foreignkey')
    # ### end Alembic commands ###
